import * as t from "io-ts";
export declare const ctEnteBeneficiario_pay_i_unqual: t.ExactType<t.IntersectionType<[t.InterfaceType<{
    identificativoUnivocoBeneficiario: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    denominazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}, t.TypeOfProps<{
    identificativoUnivocoBeneficiario: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    denominazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoBeneficiario: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    denominazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>, t.PartialType<{
    codiceUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    denomUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    indirizzoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}, t.TypeOfPartialProps<{
    codiceUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    denomUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    indirizzoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfPartialProps<{
    codiceUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    denomUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    indirizzoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>], t.TypeOfProps<{
    identificativoUnivocoBeneficiario: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    denominazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.TypeOfPartialProps<{
    codiceUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    denomUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    indirizzoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoBeneficiario: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    denominazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.OutputOfPartialProps<{
    codiceUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    denomUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    indirizzoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>, t.TypeOfProps<{
    identificativoUnivocoBeneficiario: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    denominazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.TypeOfPartialProps<{
    codiceUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    denomUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    indirizzoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoBeneficiario: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    denominazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.OutputOfPartialProps<{
    codiceUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    denomUnitOperBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    indirizzoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneBeneficiario: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>;
export declare type ctEnteBeneficiario_pay_i_unqual = t.TypeOf<typeof ctEnteBeneficiario_pay_i_unqual>;
