import * as t from "io-ts";
export declare const ctSoggettoPagatore_pay_i_unqual: t.ExactType<t.IntersectionType<[t.InterfaceType<{
    identificativoUnivocoPagatore: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}, t.TypeOfProps<{
    identificativoUnivocoPagatore: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoPagatore: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>, t.PartialType<{
    indirizzoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazionePagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailPagatore": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}, t.TypeOfPartialProps<{
    indirizzoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazionePagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailPagatore": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfPartialProps<{
    indirizzoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazionePagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailPagatore": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>], t.TypeOfProps<{
    identificativoUnivocoPagatore: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.TypeOfPartialProps<{
    indirizzoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazionePagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailPagatore": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoPagatore: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.OutputOfPartialProps<{
    indirizzoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazionePagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailPagatore": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>, t.TypeOfProps<{
    identificativoUnivocoPagatore: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.TypeOfPartialProps<{
    indirizzoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazionePagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailPagatore": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoPagatore: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.OutputOfPartialProps<{
    indirizzoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaPagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazionePagatore: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailPagatore": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>;
export declare type ctSoggettoPagatore_pay_i_unqual = t.TypeOf<typeof ctSoggettoPagatore_pay_i_unqual>;
