import * as t from "io-ts";
export declare const ctSoggettoVersante_pay_i_unqual: t.ExactType<t.IntersectionType<[t.InterfaceType<{
    identificativoUnivocoVersante: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}, t.TypeOfProps<{
    identificativoUnivocoVersante: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoVersante: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>, t.PartialType<{
    indirizzoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailVersante": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}, t.TypeOfPartialProps<{
    indirizzoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailVersante": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfPartialProps<{
    indirizzoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailVersante": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>], t.TypeOfProps<{
    identificativoUnivocoVersante: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.TypeOfPartialProps<{
    indirizzoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailVersante": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoVersante: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.OutputOfPartialProps<{
    indirizzoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailVersante": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>, t.TypeOfProps<{
    identificativoUnivocoVersante: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.TypeOfPartialProps<{
    indirizzoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailVersante": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.OutputOfProps<{
    identificativoUnivocoVersante: t.ExactType<t.IntersectionType<[t.InterfaceType<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }>, t.mixed>, t.PartialType<{}, t.TypeOfPartialProps<{}>, t.OutputOfPartialProps<{}>, t.mixed>], t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>, t.TypeOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.TypeOfPartialProps<{}>, t.OutputOfProps<{
        tipoIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 1>, import("italia-ts-commons/node_modules/io-ts").mixed>;
        codiceIdentificativoUnivoco: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    }> & t.OutputOfPartialProps<{}>, t.mixed>;
    anagraficaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
}> & t.OutputOfPartialProps<{
    indirizzoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 70>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    civicoVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    capVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 16>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    localitaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    provinciaVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, string & import("italia-ts-commons/lib/strings").IWithinRangeStringTag<1, 35>, import("italia-ts-commons/node_modules/io-ts").mixed>;
    nazioneVersante: import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Z]{2,2}">, import("italia-ts-commons/node_modules/io-ts").mixed>;
    "e-mailVersante": import("italia-ts-commons/node_modules/io-ts").Type<string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, string & import("italia-ts-commons/lib/strings").IPatternStringTag<"[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*">, import("italia-ts-commons/node_modules/io-ts").mixed>;
}>, t.mixed>;
export declare type ctSoggettoVersante_pay_i_unqual = t.TypeOf<typeof ctSoggettoVersante_pay_i_unqual>;
