import * as fs from "fs";
import * as soap from "soap";

// import interface for "PSP" service
import { IPSPPortSoap as IFespPspService } from "./wsdl-lib/FespPspService/PSPPort";

// import interfaces for "pagoPA" services (Nodo and Avvisatura)
import { IPPTPortSoap as IPagamentiTelematiciPspNodoService } from "./wsdl-lib/PagamentiTelematiciPspNodoservice/PPTPort";
import { IPPTPortSoap as IAvvisiDigitaliService } from "./wsdl-lib/AvvisiDigitaliService/PPTPort";
import { IPPTPortSoap as IIscrizioniAvvisaturaService } from "./wsdl-lib/IscrizioniAvvisaturaService/PPTPort";
import { IPPTPortSoap as INodoChiediElencoAvvisiDigitaliService } from "./wsdl-lib/NodoChiediElencoAvvisiDigitaliService/PPTPort";

// path to WSDL(s) of "PSP" service
const FespPspService_WSDL_PATH = "wsdl/nodo/NodoPerPsp.wsdl";

// path to WSDL(s) of "pagoPA" services (Nodo and Avvisatura)
const PagamentiTelematiciPspNodoService_WSDL_PATH = "wsdl/nodo/PspPerNodo.wsdl";
const AvvisiDigitaliService_WSDL_PATH = "wsdl/avvisatura/PSPPerNodoAvvisiDigitali.wsdl";
const IscrizioniAvvisaturaService_WSDL_PATH = "wsdl/avvisatura/NodoPerPSPIscrizioniAvvisatura.wsdl";
const NodoChiediElencoAvvisiDigitaliService_WSDL_PATH = "wsdl/avvisatura/NodoPerPSPChiediElencoAvvisiDigitali.wsdl";

/**
 * Helper method that wraps the creation of a WSDL client within a Promise and
 * adds the typed interfaces generated by wsdl-to-ts.
 */
function createClient<T>(wsdlUri: string, options: soap.IOptions): Promise<soap.Client & T> {
  return new Promise((resolve, reject) => {
    soap.createClient(wsdlUri, options, (err, client) => {
      if (err) {
        reject(err);
      } else {
        resolve(client as soap.Client & T);
      }
    });
  });
}

// type signature for callback based async soap methods
type SoapMethodCB<I, O> = (input: I, cb: (err: any | null, result: O, raw: string,  soapHeader: {[k: string]: any}) => any) => void;

// type signature for Promise based async soap methods
type SoapMethodPromise<I, O> = (input: I) => Promise<O>;

/**
 * Converts a SoapMethodCB into a SoapMethodPromise
 */
function promisifySoapMethod<I, O>(f: SoapMethodCB<I, O>): SoapMethodPromise<I, O> {
  return (input: I) => new Promise((resolve, reject) => {
    f(input, (err, result) => {
      if(err) {
        return reject(err);
      }
      resolve(result);
    });
  });
}

/**
 * Creates a client for the "PagamentiTelematiciPspNodo" service
 */
export function createPagamentiTelematiciPspNodoClient(options: soap.IOptions): Promise<soap.Client & IPagamentiTelematiciPspNodoService> {
  return createClient<IPagamentiTelematiciPspNodoService>(PagamentiTelematiciPspNodoService_WSDL_PATH, options);
}

/**
 * Creates a client for the "AvvisiDigitali" service
 */
export function createAvvisiDigitaliClient(options: soap.IOptions): Promise<soap.Client & IAvvisiDigitaliService> {
  return createClient<IAvvisiDigitaliService>(AvvisiDigitaliService_WSDL_PATH, options);
}

/**
 * Creates a client for the "IscrizioniAvvisatura" service
 */
export function createIscrizioniAvvisaturaClient(options: soap.IOptions): Promise<soap.Client & IIscrizioniAvvisaturaService> {
  return createClient<IIscrizioniAvvisaturaService>(IscrizioniAvvisaturaService_WSDL_PATH, options);
}

/**
 * Creates a client for the "NodoChiediElencoAvvisiDigitali" service
 */
export function createNodoChiediElencoAvvisiDigitaliClient(options: soap.IOptions): Promise<soap.Client & INodoChiediElencoAvvisiDigitaliService> {
  return createClient<INodoChiediElencoAvvisiDigitaliService>(NodoChiediElencoAvvisiDigitaliService_WSDL_PATH, options);
}

/**
 * Converts the callback based methods of a PagamentiTelematiciPspNodo client to
 * promise based methods.
 */
export class PagamentiTelematiciPspNodoAsyncClient {

  constructor(private readonly client: IPagamentiTelematiciPspNodoService) {}

  nodoVerificaRPT = promisifySoapMethod(this.client.nodoVerificaRPT)
  nodoAttivaRPT = promisifySoapMethod(this.client.nodoAttivaRPT)
  nodoInviaRT = promisifySoapMethod(this.client.nodoInviaRT)
  nodoChiediInformativaPA = promisifySoapMethod(this.client.nodoChiediInformativaPA)
  nodoChiediTemplateInformativaPSP = promisifySoapMethod(this.client.nodoChiediTemplateInformativaPSP)
  nodoInviaFlussoRendicontazione = promisifySoapMethod(this.client.nodoInviaFlussoRendicontazione)
  nodoChiediElencoQuadraturePSP = promisifySoapMethod(this.client.nodoChiediElencoQuadraturePSP)
  nodoChiediQuadraturaPSP = promisifySoapMethod(this.client.nodoChiediQuadraturaPSP)
  nodoInviaEsitoStorno = promisifySoapMethod(this.client.nodoInviaEsitoStorno)
  nodoInviaRichiestaRevoca = promisifySoapMethod(this.client.nodoInviaRichiestaRevoca)

}

/**
 * Converts the callback based methods of a AvvisiDigitali client to
 * promise based methods.
 */
export class AvvisiDigitaliAsyncClient {

  constructor(private readonly client: IAvvisiDigitaliService) {}

  pspInviaAvvisoDigitale = promisifySoapMethod(this.client.pspInviaAvvisoDigitale)

}

/**
 * Converts the callback based methods of a IscrizioniAvvisatura client to
 * promise based methods.
 */
export class IscrizioniAvvisaturaAsyncClient {

  constructor(private readonly client: IIscrizioniAvvisaturaService) {}

  nodoAggiornaIscrizioniAvvisatura = promisifySoapMethod(this.client.nodoAggiornaIscrizioniAvvisatura)

}

/**
 * Converts the callback based methods of a NodoChiediElencoAvvisiDigitali
 * client to promise based methods.
 */
export class NodoChiediElencoAvvisiDigitaliAsyncClient {

  constructor(private readonly client: INodoChiediElencoAvvisiDigitaliService) {}

  nodoChiediElencoAvvisiDigitali = promisifySoapMethod(this.client.nodoChiediElencoAvvisiDigitali)

}

/**
 * Creates a server for the PSP service.
 *
 * This function mostly wraps the `soap.listen(...)` method.
 * @see https://github.com/vpulim/node-soap#soaplistenserver-path-services-wsdl---create-a-new-soap-server-that-listens-on-path-and-provides-services
 *
 * @param server    See soap.listen documentation
 * @param path      See soap.listen documentation
 * @param handlers  An object that implements the IPSPPortSoap interface
 */
export function createPspServer(server: any, path: string, handlers: IFespPspService): Promise<soap.Server> {
  return new Promise((resolve, reject) => {
    fs.readFile(PagamentiTelematiciPspNodoService_WSDL_PATH, { encoding: "UTF-8" }, (err, wsdl) => {
      if (err) {
        return reject(err);
      }
      const service = {
        FespPspService: {
          PSPPort: handlers,
        },
      };

      resolve(soap.listen(server, path, service, wsdl));
    });

  });
}
