
import * as clients from "./clients";
import * as servers from "./servers";
import * as cdInfoPagamento_ppt from "../yaml-to-ts/cdInfoPagamento_ppt";
import * as cdInfoPagamentoHeader from "../yaml-to-ts/cdInfoPagamentoHeader";
import * as cdInfoPagamentoInput from "../yaml-to-ts/cdInfoPagamentoInput";
import * as cdInfoPagamentoOutput from "../yaml-to-ts/cdInfoPagamentoOutput";
import * as cdInfoPagamentoResponse_ppt from "../yaml-to-ts/cdInfoPagamentoResponse_ppt";
import * as ctEnteBeneficiario_pay_i_unqual from "../yaml-to-ts/ctEnteBeneficiario_pay_i_unqual";
import * as ctFaultBean_ppt from "../yaml-to-ts/ctFaultBean_ppt";
import * as ctIdentificativoUnivocoPersonaFG_pay_i from "../yaml-to-ts/ctIdentificativoUnivocoPersonaFG_pay_i";
import * as ctIdentificativoUnivocoPersonaG_pay_i from "../yaml-to-ts/ctIdentificativoUnivocoPersonaG_pay_i";
import * as ctSoggettoPagatore_pay_i_unqual from "../yaml-to-ts/ctSoggettoPagatore_pay_i_unqual";
import * as ctSoggettoVersante_pay_i_unqual from "../yaml-to-ts/ctSoggettoVersante_pay_i_unqual";
import * as ctSpezzoneStrutturatoCausaleVersamento_ppt from "../yaml-to-ts/ctSpezzoneStrutturatoCausaleVersamento_ppt";
import * as ctSpezzoniCausaleVersamento_ppt from "../yaml-to-ts/ctSpezzoniCausaleVersamento_ppt";
import * as esitoNodoAttivaRPTRisposta_ppt from "../yaml-to-ts/esitoNodoAttivaRPTRisposta_ppt";
import * as esitoNodoInviaRTRisposta_ppt from "../yaml-to-ts/esitoNodoInviaRTRisposta_ppt";
import * as esitoNodoVerificaRPTRisposta_ppt from "../yaml-to-ts/esitoNodoVerificaRPTRisposta_ppt";
import * as faultBean_ppt from "../yaml-to-ts/faultBean_ppt";
import * as nodoAttivaRPT_ppt from "../yaml-to-ts/nodoAttivaRPT_ppt";
import * as nodoAttivaRPTHeader from "../yaml-to-ts/nodoAttivaRPTHeader";
import * as nodoAttivaRPTInput from "../yaml-to-ts/nodoAttivaRPTInput";
import * as nodoAttivaRPTOutput from "../yaml-to-ts/nodoAttivaRPTOutput";
import * as nodoAttivaRPTRisposta_ppt from "../yaml-to-ts/nodoAttivaRPTRisposta_ppt";
import * as nodoChiediElencoQuadraturePSP_ppt from "../yaml-to-ts/nodoChiediElencoQuadraturePSP_ppt";
import * as nodoChiediElencoQuadraturePSPHeader from "../yaml-to-ts/nodoChiediElencoQuadraturePSPHeader";
import * as nodoChiediElencoQuadraturePSPInput from "../yaml-to-ts/nodoChiediElencoQuadraturePSPInput";
import * as nodoChiediElencoQuadraturePSPOutput from "../yaml-to-ts/nodoChiediElencoQuadraturePSPOutput";
import * as nodoChiediElencoQuadraturePSPRisposta_ppt from "../yaml-to-ts/nodoChiediElencoQuadraturePSPRisposta_ppt";
import * as nodoChiediInformativaPA_ppt from "../yaml-to-ts/nodoChiediInformativaPA_ppt";
import * as nodoChiediInformativaPAHeader from "../yaml-to-ts/nodoChiediInformativaPAHeader";
import * as nodoChiediInformativaPAInput from "../yaml-to-ts/nodoChiediInformativaPAInput";
import * as nodoChiediInformativaPAOutput from "../yaml-to-ts/nodoChiediInformativaPAOutput";
import * as nodoChiediInformativaPARisposta_ppt from "../yaml-to-ts/nodoChiediInformativaPARisposta_ppt";
import * as nodoChiediQuadraturaPSP_ppt from "../yaml-to-ts/nodoChiediQuadraturaPSP_ppt";
import * as nodoChiediQuadraturaPSPHeader from "../yaml-to-ts/nodoChiediQuadraturaPSPHeader";
import * as nodoChiediQuadraturaPSPInput from "../yaml-to-ts/nodoChiediQuadraturaPSPInput";
import * as nodoChiediQuadraturaPSPOutput from "../yaml-to-ts/nodoChiediQuadraturaPSPOutput";
import * as nodoChiediQuadraturaPSPRisposta_ppt from "../yaml-to-ts/nodoChiediQuadraturaPSPRisposta_ppt";
import * as nodoChiediTemplateInformativaPSP_ppt from "../yaml-to-ts/nodoChiediTemplateInformativaPSP_ppt";
import * as nodoChiediTemplateInformativaPSPHeader from "../yaml-to-ts/nodoChiediTemplateInformativaPSPHeader";
import * as nodoChiediTemplateInformativaPSPInput from "../yaml-to-ts/nodoChiediTemplateInformativaPSPInput";
import * as nodoChiediTemplateInformativaPSPOutput from "../yaml-to-ts/nodoChiediTemplateInformativaPSPOutput";
import * as nodoChiediTemplateInformativaPSPRisposta_ppt from "../yaml-to-ts/nodoChiediTemplateInformativaPSPRisposta_ppt";
import * as nodoInviaEsitoStorno_ppt from "../yaml-to-ts/nodoInviaEsitoStorno_ppt";
import * as nodoInviaEsitoStornoHeader from "../yaml-to-ts/nodoInviaEsitoStornoHeader";
import * as nodoInviaEsitoStornoInput from "../yaml-to-ts/nodoInviaEsitoStornoInput";
import * as nodoInviaEsitoStornoOutput from "../yaml-to-ts/nodoInviaEsitoStornoOutput";
import * as nodoInviaEsitoStornoRisposta_ppt from "../yaml-to-ts/nodoInviaEsitoStornoRisposta_ppt";
import * as nodoInviaFlussoRendicontazione_ppt from "../yaml-to-ts/nodoInviaFlussoRendicontazione_ppt";
import * as nodoInviaFlussoRendicontazioneHeader from "../yaml-to-ts/nodoInviaFlussoRendicontazioneHeader";
import * as nodoInviaFlussoRendicontazioneInput from "../yaml-to-ts/nodoInviaFlussoRendicontazioneInput";
import * as nodoInviaFlussoRendicontazioneOutput from "../yaml-to-ts/nodoInviaFlussoRendicontazioneOutput";
import * as nodoInviaFlussoRendicontazioneRisposta_ppt from "../yaml-to-ts/nodoInviaFlussoRendicontazioneRisposta_ppt";
import * as nodoInviaRichiestaRevoca_ppt from "../yaml-to-ts/nodoInviaRichiestaRevoca_ppt";
import * as nodoInviaRichiestaRevocaHeader from "../yaml-to-ts/nodoInviaRichiestaRevocaHeader";
import * as nodoInviaRichiestaRevocaInput from "../yaml-to-ts/nodoInviaRichiestaRevocaInput";
import * as nodoInviaRichiestaRevocaOutput from "../yaml-to-ts/nodoInviaRichiestaRevocaOutput";
import * as nodoInviaRichiestaRevocaRisposta_ppt from "../yaml-to-ts/nodoInviaRichiestaRevocaRisposta_ppt";
import * as nodoInviaRT_ppt from "../yaml-to-ts/nodoInviaRT_ppt";
import * as nodoInviaRTHeader from "../yaml-to-ts/nodoInviaRTHeader";
import * as nodoInviaRTInput from "../yaml-to-ts/nodoInviaRTInput";
import * as nodoInviaRTOutput from "../yaml-to-ts/nodoInviaRTOutput";
import * as nodoInviaRTRisposta_ppt from "../yaml-to-ts/nodoInviaRTRisposta_ppt";
import * as nodoTipoCodiceIdRPT_ppt from "../yaml-to-ts/nodoTipoCodiceIdRPT_ppt";
import * as nodoTipoDatiPagamentoPA_ppt from "../yaml-to-ts/nodoTipoDatiPagamentoPA_ppt";
import * as nodoTipoDatiPagamentoPSP_ppt from "../yaml-to-ts/nodoTipoDatiPagamentoPSP_ppt";
import * as nodoVerificaRPT_ppt from "../yaml-to-ts/nodoVerificaRPT_ppt";
import * as nodoVerificaRPTHeader from "../yaml-to-ts/nodoVerificaRPTHeader";
import * as nodoVerificaRPTInput from "../yaml-to-ts/nodoVerificaRPTInput";
import * as nodoVerificaRPTOutput from "../yaml-to-ts/nodoVerificaRPTOutput";
import * as nodoVerificaRPTRisposta_ppt from "../yaml-to-ts/nodoVerificaRPTRisposta_ppt";
import * as risposta_ppt from "../yaml-to-ts/risposta_ppt";
import * as Security from "../yaml-to-ts/Security";
import * as stEMail_pay_i from "../yaml-to-ts/stEMail_pay_i";
import * as stImporto_ppt from "../yaml-to-ts/stImporto_ppt";
import * as stNazioneProvincia_pay_i from "../yaml-to-ts/stNazioneProvincia_pay_i";
import * as stPassword_ppt from "../yaml-to-ts/stPassword_ppt";
import * as stText16_pay_i from "../yaml-to-ts/stText16_pay_i";
import * as stText25_ppt from "../yaml-to-ts/stText25_ppt";
import * as stText35_pay_i from "../yaml-to-ts/stText35_pay_i";
import * as stText35_ppt from "../yaml-to-ts/stText35_ppt";
import * as stText70_pay_i from "../yaml-to-ts/stText70_pay_i";
import * as stText140_ppt from "../yaml-to-ts/stText140_ppt";
import * as stTipoIdentificativoUnivocoPersFG_pay_i from "../yaml-to-ts/stTipoIdentificativoUnivocoPersFG_pay_i";
import * as stTipoIdentificativoUnivocoPersG_pay_i from "../yaml-to-ts/stTipoIdentificativoUnivocoPersG_pay_i";
import * as tipoIdQuadratura_ppt from "../yaml-to-ts/tipoIdQuadratura_ppt";
import * as tipoListaQuadrature_ppt from "../yaml-to-ts/tipoListaQuadrature_ppt";

// re-export all the interfaces
export { clients };
export { servers };
export {cdInfoPagamento_ppt };
export {cdInfoPagamentoHeader };
export {cdInfoPagamentoInput };
export {cdInfoPagamentoOutput };
export {cdInfoPagamentoResponse_ppt };
export {ctEnteBeneficiario_pay_i_unqual };
export {ctFaultBean_ppt };
export {ctIdentificativoUnivocoPersonaFG_pay_i};
export {ctIdentificativoUnivocoPersonaG_pay_i};
export {ctSoggettoPagatore_pay_i_unqual };
export {ctSoggettoVersante_pay_i_unqual };
export {ctSpezzoneStrutturatoCausaleVersamento_ppt};
export {ctSpezzoniCausaleVersamento_ppt };
export {esitoNodoAttivaRPTRisposta_ppt };
export {esitoNodoInviaRTRisposta_ppt };
export {esitoNodoVerificaRPTRisposta_ppt };
export {faultBean_ppt };
export {nodoAttivaRPT_ppt };
export {nodoAttivaRPTHeader };
export {nodoAttivaRPTInput };
export {nodoAttivaRPTOutput };
export {nodoAttivaRPTRisposta_ppt };
export {nodoChiediElencoQuadraturePSP_ppt };
export {nodoChiediElencoQuadraturePSPHeader };
export {nodoChiediElencoQuadraturePSPInput };
export {nodoChiediElencoQuadraturePSPOutput };
export {nodoChiediElencoQuadraturePSPRisposta_ppt};
export {nodoChiediInformativaPA_ppt };
export {nodoChiediInformativaPAHeader };
export {nodoChiediInformativaPAInput };
export {nodoChiediInformativaPAOutput };
export {nodoChiediInformativaPARisposta_ppt };
export {nodoChiediQuadraturaPSP_ppt };
export {nodoChiediQuadraturaPSPHeader };
export {nodoChiediQuadraturaPSPInput };
export {nodoChiediQuadraturaPSPOutput };
export {nodoChiediQuadraturaPSPRisposta_ppt };
export {nodoChiediTemplateInformativaPSP_ppt };
export {nodoChiediTemplateInformativaPSPHeader};
export {nodoChiediTemplateInformativaPSPInput};
export {nodoChiediTemplateInformativaPSPOutput};
export {nodoChiediTemplateInformativaPSPRisposta_ppt};
export {nodoInviaEsitoStorno_ppt };
export {nodoInviaEsitoStornoHeader };
export {nodoInviaEsitoStornoInput };
export {nodoInviaEsitoStornoOutput };
export {nodoInviaEsitoStornoRisposta_ppt };
export {nodoInviaFlussoRendicontazione_ppt };
export {nodoInviaFlussoRendicontazioneHeader };
export {nodoInviaFlussoRendicontazioneInput };
export {nodoInviaFlussoRendicontazioneOutput };
export {nodoInviaFlussoRendicontazioneRisposta_ppt};
export {nodoInviaRichiestaRevoca_ppt };
export {nodoInviaRichiestaRevocaHeader };
export {nodoInviaRichiestaRevocaInput };
export {nodoInviaRichiestaRevocaOutput };
export {nodoInviaRichiestaRevocaRisposta_ppt };
export {nodoInviaRT_ppt };
export {nodoInviaRTHeader };
export {nodoInviaRTInput };
export {nodoInviaRTOutput };
export {nodoInviaRTRisposta_ppt };
export {nodoTipoCodiceIdRPT_ppt };
export {nodoTipoDatiPagamentoPA_ppt };
export {nodoTipoDatiPagamentoPSP_ppt };
export {nodoVerificaRPT_ppt };
export {nodoVerificaRPTHeader };
export {nodoVerificaRPTInput };
export {nodoVerificaRPTOutput };
export {nodoVerificaRPTRisposta_ppt };
export {risposta_ppt };
export {Security };
export {stEMail_pay_i };
export {stImporto_ppt };
export {stNazioneProvincia_pay_i };
export {stPassword_ppt };
export {stText16_pay_i };
export {stText25_ppt };
export {stText35_pay_i };
export {stText35_ppt };
export {stText70_pay_i };
export {stText140_ppt };
export {stTipoIdentificativoUnivocoPersFG_pay_i};
export {stTipoIdentificativoUnivocoPersG_pay_i};
export {tipoIdQuadratura_ppt };
export {tipoListaQuadrature_ppt };
